// THIS FILE IS AUTOGENERATED
// DO NOT EDIT THIS FILE!

import "@algolia/autocomplete-theme-classic";
import "./index.css";
const lunr = require("@cmfcmf/docusaurus-search-local/lib/lunr");
export const tokenize = (input) =>
  lunr.tokenizer(input).map((token) => token.str);
export const mylunr = lunr;
